### ISSUE TITLE
2016. 06. 22 참석 어려우신분들 집계

### ISSUE THREAD

**Issue by SeongUgJung** [gdgand/android-rxjava#10]
댓글 남겨주세요.

**Comment by hassanabidpk** [comment]
내일 불참  (회사 일 때문에 💻 ) 😢  ~ 다음 주 부터 계속 참석 할거예요 ~ 👍

**Comment by dalinaum** [comment]
저도 내일 불참이에요 ㅜㅜ

**Comment by ruicara** [comment]
저도 오늘 야근이요. 스터디할려니 바빠지네요 ㅜ.ㅜ

**Comment by ruicara** [comment]
ruicara -> yunny 입니다. 깃허브랑 슬랙이랑 제 아이디가 다르네요

**Comment by hayden-han** [comment]
개인사정으로 불참입니다ㅜ 다음주에 뵐게요 :)
