### ISSUE TITLE
2016. 06. 29 스터디 불참자 조사

### ISSUE THREAD

**Issue by SeongUgJung** [gdgand/android-rxjava#16]
댓글에 남겨주세요~

**Comment by ruicara** [comment]
슬랙 아이디: yunny
저는 요즘 계속 야근이예요. 불참입니다. ㅠ.ㅠ

**Comment by Nebu1eto** [comment]
회사에 전사회의가 잡혀서 못가게 되었습니다. 죄송합니다 ㅠㅠㅠ

**Comment by smalljiny** [comment]
슬랙 아이디 :  mario
오늘 개인사정이 생겨 참석 못하게 되었습니다.

**Comment by hassanabidpk** [comment]
Drowned in Unity plugin code - Can't come today :cry

**Comment by mugku** [comment]
죄송합니다. 개인사정으로 못가게 되었습니다.

**Comment by ggikko** [comment]
슬랙 아이디 : ggikkopark
출시가 몇일 남지 않아 불참합니다. 죄송합니다. :(
