### ISSUE TITLE
7/20 스터디 불참자

### ISSUE THREAD

**Issue by SeongUgJung** [gdgand/android-rxjava#25]
댓글남겨주세요~

**Comment by ruicara** [comment]
제 프로젝트 일정이 8월말까지 너무 바쁩니다.
죄송한데 명단에서 삭제 해주세요. 
참여를 원하시는 분이 많으신 것 같은데 아예 제가 명단에서 빠지는게 좋을 것 같습니다.
좋은 스터디 참여를 못해서 너무 아쉽습니다.

**Comment by ruicara** [comment]
제 슬랙 아이디는 yunny 입니다.

**Comment by kunny** [comment]
@ruicara 네 알겠습니다. 다음 기회에 함께 할 수 있으면 좋겠습니다 :)

**Comment by Nebu1eto** [comment]
몸이 안 좋아서 이번 주는 힘들 것 같습니다.
커니님의 이야기를 듣고 싶었는데 너무 아쉽네요.

푹 쉬고 다음번에 뵙겠습니다. (@realignist)

**Comment by hmm-umm** [comment]
급 일정에 변동이 생겨 참여하기 어려울 것 같습니다.ㅜㅜ 죄송합니다.

**Comment by kyungin-park** [comment]
무한빌드중입니다 ㅠㅠ 못갈 가능성이 크네요. 일단 불참으로 등록해주세여 ㅠㅠ

**Comment by SeongUgJung** [comment]
---마감----
다음 기회에 뵈요~

다음 스터디는 8/3 입니다~

다음주는 gdg 정기모임에서 뵈요~
