### ISSUE TITLE
7/20 스터디 객원

### ISSUE THREAD

**Issue by SeongUgJung** [gdgand/android-rxjava#26]
댓글 남겨주세요

**Comment by maryang710** [comment]
참여합니다.
슬랙id: rfrost

**Comment by Ahnmuke** [comment]
참여하고 싶어용~ 슬랙id : amw

**Comment by kunny** [comment]
@rfrost77 @Ahnmuke 슬랙 id도 함께 남겨주세요~~

**Comment by uno-dos** [comment]
안녕하세요~
참여신청 스을쩍 남겨놓습니다.
슬랙: uno.kim

**Comment by sleepbear669** [comment]
안녕하세요 gg
참여신청 합니다. 
slack id : sleepbear
입니다.

**Comment by SeongUgJung** [comment]
댓글 남기신분들 오시면 되요~
추가로 오실분들도 댓글만 남겨주세요~
