### ISSUE TITLE
2016. 08. 03 스터디 불참자 조사

### ISSUE THREAD

**Issue by SeongUgJung** [gdgand/android-rxjava#28]
댓글로
Slack : id
를 남겨주세요~

**Comment by steadymoka** [comment]
Slack: moka
일이 생겨서 못가게 되었습니다 ㅠ 영상 촬영이 안되어  넘나 아쉽네요 ㅜ

**Comment by moltak** [comment]
Slack : moltak 
개인 사정이 생겨서 못가게 되었습니다. ㅠㅡㅠ

**Comment by gaemi** [comment]
Slack : gaemi
개인 사정으로 못가게 되었습니다.

**Comment by hmm-umm** [comment]
slack: mugku
죄송합니다. 개인사정으로 못가게 되었습니다.

**Comment by ggikko** [comment]
Slack : ggikko park
출시가 몇일 남지 않아 불참합니다. 죄송합니다. ㅠ

**Comment by Nebu1eto** [comment]
Slack: realignist

계속 건강상의 이유로 불참하게 되네요. 개인적으로 정말 기대하고 있던 부분이라 더욱 아쉬운 것 같습니다. 죄송합니다 ㅠㅠ

**Comment by SeongUgJung** [comment]
네 다음 기회에 뵈요~
